### ISSUE TITLE
扫码效率貌似有些慢

### ISSUE THREAD

**Issue by bj6785** [MRYangY/YZxing#1]
用微信钱包的二维码扫码，在对准二维码的情况下要5s多才能得出结果

**Comment by MRYangY** [comment]
是微信钱包收付款的二维码么？我这边扫码效率很高。  
YZxing是基于zxing的，zxing它底层算法没有微信，支付宝等大厂他们自己研发的算法好。所以在复杂的二维码环境下没有他们的效率高，一般正常的码，扫码效率还是很快的。
