### ISSUE TITLE
扫描要对半天才出结果，还有返回的结果怎么改呢

### ISSUE THREAD

**Issue by 214024475** [MRYangY/YZxing#2]
扫描要对半天才出结果，还有返回的结果怎么改呢？  返回的是什么库名http什么的   还有这句代码怎么加呢？添加 hints.put(DecodeHintType.TRY_HARDER, true);语句，能够提高扫码精确度，准确率

**Comment by MRYangY** [comment]
hints.put(DecodeHintType.TRY_HARDER, true);这句话库里已经加过了。
我写的关于扫码的博客，有关于yzxing库的使用说明。可以去看看
