### ISSUE TITLE
build.gradle

### ISSUE THREAD

**Issue by DeathsKnights** [MRYangY/YZxing#3]
Yzxing下载到本地库build.gradle 怎么修改啊 有些包没有

**Comment by MRYangY** [comment]
是不是apply plugin: 'com.jfrog.bintray'这一块爆红？在你项目的build.gradle文件中dependencies闭包下加入：
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'

就可以了。
或者：
Yzxing库模块下的build.gradle文件中的一些引用是为了上传Yzxing库到Jcenter上面用的，比如apply plugin: 'com.jfrog.bintray'，版本号，install闭包等这类的groove语句可以自己手动删除掉。不影响库的使用的。
